seeds:
  - name: unit_test_input_dim_dates
    config:
      column_types:
        CALENDAR_DATE: DATE
        DATE_WEEK: DATE
        DATE_MONTH: DATE
        DATE_QUARTER: DATE
        DATE_YEAR: DATE
        DAY_OF_MONTH: NUMBER(38, 0)
        YEAR_NUM: NUMBER(38, 0)
        QUARTER_NUM: NUMBER(38, 0)
        MONTH_NUM: NUMBER(38, 0)
  - name: unit_test_input_dim_subscriptions
    config:
      column_types:
        SUBSCRIPTION_ID: NUMBER(38, 0)
        SUBSCRIPTION_PLAN_ID: NUMBER(38, 0)
        USER_ID: NUMBER(38, 0)
        STARTS_AT: TIMESTAMP_NTZ
        ENDS_AT: TIMESTAMP_NTZ
        PLAN_NAME: VARCHAR(128)
        PRICING: FLOAT
        BILLING_PERIOD: VARCHAR(128)
  - name: unit_test_output_mrr
    config:
      column_types:
        SURROGATE_KEY: VARCHAR
        DATE_MONTH: DATE
        USER_ID: NUMBER(38, 0)
        SUBSCRIPTION_ID: NUMBER(38, 0)
        STARTS_AT: TIMESTAMP_NTZ
        ENDS_AT: TIMESTAMP_NTZ
        PLAN_NAME: VARCHAR
        MRR_AMOUNT: FLOAT
        MRR_CHANGE: FLOAT
        RETAINED_MRR_AMOUNT: FLOAT
        PREVIOUS_MONTH_MRR_AMOUNT: FLOAT
        CHANGE_CATEGORY: VARCHAR
        MONTH_RETAINED_NUMBER: NUMBER(38, 0)
